### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by umpirsky**

### CODE REVIEW

**Comment by docteurklein** [comment]
you, sir are too good. Not sure why travis falis tho.

**Comment by umpirsky** [comment]
@docteurklein For some reason it fails to install dist. Let me try without...

**Comment by umpirsky** [comment]
@docteurklein Only PHP 5.4 fails. What to do?

**Comment by docteurklein** [comment]
let's drop it !

**Comment by docteurklein** [comment]
will release a new major tag

**Comment by umpirsky** [comment]
@docteurklein Smart boy. :+1:

**Comment by umpirsky** [comment]
@docteurklein Green.

**Comment by docteurklein** [comment]
how should we release this (cc @tyx ).
we have 1.0.0, but php version changed). 
Should it be 2.0.0 ?

**Comment by tyx** [comment]
5.4 is no longer supported by php. For me it is not a BC break ! So let's go for a 1.1.0 ?

**Comment by docteurklein** [comment]
thanks for the answer :)
doctrine/cache for example did the same, a minor release changed the php req.
Ok let's do this 1.1.0 then.

**Comment by docteurklein** [comment]
done. 
thanks!

**Comment by tyx** [comment]
:+1:

**Comment by shouze** [comment]
Readme needs an update too as it's now a php 5.5+ lib ;)

**Comment by shouze** [comment]
README Fixed by https://github.com/docteurklein/php-etl/pull/33

**Pull request merged**
